### ISSUE TITLE
docker启动后没有生成视频

### ISSUE THREAD

**Issue by 404name** [easychen/windrecorder#1]
照着b站教程走的，没能实现视频输出。
docker运行输出如下。。
手动start和stop也没有

`24/07/2021 01:07:30 Xinerama is present and active (e.g. multi-head).
24/07/2021 01:07:30 Xinerama: number of sub-screens: 1
24/07/2021 01:07:30 Xinerama: no blackouts needed (only one sub-screen)
24/07/2021 01:07:30
24/07/2021 01:07:30 fb read rate: 1854 MB/sec
24/07/2021 01:07:30 fast read: reset -wait  ms to: 10
24/07/2021 01:07:30 fast read: reset -defer ms to: 10
24/07/2021 01:07:30 The X server says there are 10 mouse buttons.
PORT=5900
24/07/2021 01:07:30 screen setup finished.
24/07/2021 01:07:30
24/07/2021 01:07:30 WARNING: You are running x11vnc WITHOUT a password.  See
24/07/2021 01:07:30 WARNING: the warning message printed above for more info.
24/07/2021 01:07:30

The VNC desktop is:      245673dacd90:0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching
`

**Comment by easychen** [comment]
再次测试了下，WindRecorder 本身并没有问题。但 windmark.pro 服务部署在海外，内地网络访问可能会超时导致录制失败，建议参考文档录制本地网页（demo目录下）进行测试。

windmark 我们看稍后是否需要在内地也部署一套以提升速度。

issue 我先关了，如果录制本地网页也遇到问题，请重开。

**Comment by easychen** [comment]
![image](https://user-images.githubusercontent.com/1294760/126886532-df6eede4-df22-4f86-96fa-4264a8971fd7.png)

windmark 新增了区域设置，切换的大陆后资源文件会使用内地存储

**Comment by 404name** [comment]
好的好的😁
