### ISSUE TITLE
docker命令启动录制有两个问题

### ISSUE THREAD

**Issue by towelong** [easychen/windrecorder#2]
- 1. 启动录制后前大概18秒左右有个黑屏
- 2. 字幕消失不见了

**Comment by easychen** [comment]
黑屏一般是因为网络延迟加载资源导致，可以传个 preload=1 试试。字幕默认是关的（但在编辑界面会显示），确认最上边配置中不是 subtitle:off

**Comment by towelong** [comment]
> 黑屏一般是因为网络延迟加载资源导致，可以传个 preload=1 试试。字幕默认是关的（但在编辑界面会显示），确认最上边配置中不是 subtitle:off

好的我试试
